-- Report Queue Table - Schema Documentation
-- This file documents the expected report_queue table structure
-- 
-- ✅ TABLE ALREADY EXISTS IN YOUR DATABASE
-- No SQL execution needed - your existing table is compatible!
--
-- Your current table structure:
-- - id (auto increment primary key)
-- - field_id (foreign key to fields table)
-- - trigger_type: 'new_field','field_update','loss_event','growth_stage_change'
-- - priority: 'low','normal','high','urgent'
-- - status: 'pending','processing','completed','failed'
-- - retry_count (integer, default 0)
-- - error_message (text, nullable)
-- - created_at (timestamp, default current_timestamp)
-- - processed_at (timestamp, nullable)
--
-- ✅ COMPATIBILITY CONFIRMED
-- Your existing table structure is fully compatible with the reporting service.
-- 
-- Current pending reports: 18 field reports ready for processing
-- These will be automatically processed once the service is deployed.
--
-- No database changes required!
